const STORAGE_KEY = 'paranseon-food-records-v1';
const GUIDE_KEY = 'paranseon-guide-seen-v1';
const $ = (selector) => document.querySelector(selector);
const todayKey = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const todayText = () => new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'long'}).format(new Date());
let records = readRecords();
let photoData = '';
let currentTab = 'text';
let guidePage = 0;
let toastTimer;

function readRecords(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(saved)?saved.filter(item=>item&&typeof item.name==='string'):[];}catch{return [];}}
function saveRecords(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(records));}catch{showToast('저장 공간이 부족해요','사진을 줄이거나 이전 기록을 삭제한 후 다시 시도해 주세요.');}}
function todayRecords(){return records.filter(item=>item.date===todayKey());}
function numberText(value){return Number(value.toFixed(1)).toLocaleString('ko-KR',{maximumFractionDigits:1});}
function scoreFor(items){const carbs=items.reduce((sum,item)=>sum+Number(item.carbs||0),0);const sugar=items.reduce((sum,item)=>sum+Number(item.sugar||0),0);return {carbs,sugar,score:carbs+0.25*sugar};}
function levelFor(score){return score>=100?'high':score>=50?'medium':'good';}
function showToast(title,copy){$('#toast-title').textContent=title;$('#toast-copy').textContent=copy;$('#alert-toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('#alert-toast').hidden=true;},7000);}
function render(){const items=todayRecords();const {carbs,sugar,score}=scoreFor(items);const level=levelFor(score);const percent=Math.min(score,100);const label={good:'적절',medium:'보통',high:'위험'}[level];const copy={good:items.length?'지금까지의 기록은 적절 단계예요.':'아직 기록이 없어요. 첫 음식을 남겨보세요.',medium:'오늘의 탄수화물 기록이 늘었어요. 다음 음식을 선택할 때 참고해 주세요.',high:'혈당 스파이크 가능성에 주의하세요. 실제 상태는 혈당 측정으로 확인해 주세요.'}[level];
  $('#risk-label').textContent=label;$('#risk-label').className=`risk-title ${level}`;$('#risk-copy').textContent=copy;$('#total-carb').innerHTML=`${numberText(carbs)}<small>g</small>`;$('#total-sugar').innerHTML=`${numberText(sugar)}<small>g</small>`;$('#total-items').innerHTML=`${items.length}<small>개</small>`;$('#gauge-progress').style.setProperty('--progress',`${percent}%`);$('#gauge-percent').textContent=`${Math.round(percent)}% 채움`;$('#gauge-progress').setAttribute('aria-valuenow',String(Math.round(percent)));$('#gauge-progress').setAttribute('aria-valuetext',`${label} 단계, 오늘 탄수화물 ${numberText(carbs)}그램`);$('#history-count').textContent=items.length;$('#history-date').textContent=todayText();$('#today-date').textContent=todayText();
  const list=$('#history-list');list.replaceChildren();if(!items.length){const empty=document.createElement('div');empty.className='empty-state';empty.innerHTML='<strong>아직 기록한 음식이 없어요</strong><p>첫 식사를 추가하면 이곳에 차곡차곡 모입니다.</p>';list.append(empty);return;}
  [...items].reverse().forEach(item=>{const row=document.createElement('div');row.className='history-item';const thumb=document.createElement('div');thumb.className='history-thumb';if(item.photo){const img=document.createElement('img');img.src=item.photo;img.alt='';thumb.append(img);}else{thumb.textContent=item.name.trim().charAt(0)||'식';}const main=document.createElement('div');main.className='history-main';const name=document.createElement('strong');name.textContent=item.name;const time=document.createElement('span');time.textContent=new Intl.DateTimeFormat('ko-KR',{hour:'numeric',minute:'2-digit'}).format(new Date(item.createdAt));main.append(name,time);const nutrients=document.createElement('div');nutrients.className='history-nutrients';nutrients.textContent=`탄수화물 ${numberText(Number(item.carbs))}g`;const s=document.createElement('span');s.textContent='|';nutrients.append(s,document.createTextNode(`당류 ${numberText(Number(item.sugar))}g`));const del=document.createElement('button');del.type='button';del.className='delete-item';del.textContent='×';del.setAttribute('aria-label',`${item.name} 기록 삭제`);del.addEventListener('click',()=>{records=records.filter(record=>record.id!==item.id);saveRecords();render();showToast('기록을 삭제했어요','게이지가 오늘의 기록에 맞게 다시 계산되었습니다.');});row.append(thumb,main,nutrients,del);list.append(row);});}

function setTab(tab){currentTab=tab;document.querySelectorAll('.entry-tab').forEach(button=>{const active=button.dataset.tab===tab;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));});$('#photo-area').classList.toggle('hidden',tab!=='photo');}
document.querySelectorAll('.entry-tab').forEach(button=>button.addEventListener('click',()=>setTab(button.dataset.tab)));
$('#photo-button').addEventListener('click',()=>$('#photo-input').click());
$('#photo-input').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){showToast('이미지 파일을 선택해 주세요','JPG, PNG 등 음식 사진을 첨부할 수 있어요.');return;}try{photoData=await resizeImage(file);$('#photo-image').src=photoData;$('#photo-preview').classList.remove('hidden');$('#photo-button-text').textContent='다른 사진 선택';}catch{showToast('사진을 불러오지 못했어요','다른 이미지 파일을 선택해 주세요.');}});
$('#remove-photo').addEventListener('click',()=>{photoData='';$('#photo-input').value='';$('#photo-preview').classList.add('hidden');$('#photo-button-text').textContent='사진 촬영 또는 파일 선택';});
function resizeImage(file){return new Promise((resolve,reject)=>{const img=new Image();const url=URL.createObjectURL(file);img.onload=()=>{const scale=Math.min(1,1000/img.width,1000/img.height);const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',.74));};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('image'));};img.src=url;});}
$('#food-form').addEventListener('submit',event=>{event.preventDefault();const name=$('#food-name').value.trim();const carbRaw=$('#carbs').value.trim();const sugarRaw=$('#sugar').value.trim();const carb=Number(carbRaw);const sugar=sugarRaw===''?0:Number(sugarRaw);const error=$('#form-error');error.hidden=true;if(!name){error.textContent='음식 이름을 입력해 주세요.';error.hidden=false;$('#food-name').focus();return;}if(currentTab==='photo'&&!photoData){error.textContent='사진을 촬영하거나 파일을 선택해 주세요.';error.hidden=false;$('#photo-button').focus();return;}if(carbRaw===''||!Number.isFinite(carb)||carb<0||carb>500){error.textContent='탄수화물은 0~500g 사이로 입력해 주세요.';error.hidden=false;$('#carbs').focus();return;}if(!Number.isFinite(sugar)||sugar<0||sugar>carb){error.textContent='당류는 0g 이상, 탄수화물 이하로 입력해 주세요.';error.hidden=false;$('#sugar').focus();return;}const before=levelFor(scoreFor(todayRecords()).score);records.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random(),date:todayKey(),createdAt:new Date().toISOString(),name,carbs:carb,sugar,photo:currentTab==='photo'?photoData:''});saveRecords();render();$('#food-form').reset();$('#remove-photo').click();const after=levelFor(scoreFor(todayRecords()).score);if(after==='high')showToast('혈당 스파이크 주의','오늘 기록이 위험 단계에 도달했어요. 실제 혈당은 측정으로 확인해 주세요.');else if(after==='medium'&&before==='good')showToast('보통 단계에 도달했어요','오늘의 탄수화물 기록이 쌓이고 있어요.');else showToast('기록을 추가했어요','오늘의 게이지에 반영되었습니다.');});
$('#close-toast').addEventListener('click',()=>{$('#alert-toast').hidden=true;});

const guide=[{title:'먹은 음식을\n간단히 남겨주세요',description:'음식 이름과 영양성분표의 탄수화물·당류를 입력하면 오늘의 기록에 바로 쌓입니다.',detail:'사진 탭에서는 음식을 촬영하거나 사진을 첨부할 수 있어요. 사진 속 영양정보는 자동 분석되지 않으니 수치를 직접 적어주세요.'},{title:'게이지로 오늘의 흐름을\n확인하세요',description:'기록이 쌓일수록 게이지가 움직이고, 적절·보통·위험 단계가 바뀌면 화면에서 알려드려요.',detail:'게이지는 실제 혈당값이 아닌 앱의 참고 지표예요. 스파이크 여부는 혈당 측정으로 확인해 주세요.'}];
function renderGuide(){const page=guide[guidePage];$('#guide-step').textContent=`0${guidePage+1} / 02`;$('#guide-title').textContent=page.title;$('#guide-title').style.whiteSpace='pre-line';$('#guide-description').textContent=page.description;$('#guide-detail').textContent=page.detail;$('#guide-next').textContent=guidePage===1?'기록 시작하기':'다음';document.querySelectorAll('.guide-dots span').forEach((dot,index)=>dot.classList.toggle('active',index===guidePage));}
function openGuide(){guidePage=0;renderGuide();$('#guide-modal').hidden=false;$('#close-guide').focus();}
function closeGuide(){localStorage.setItem(GUIDE_KEY,'true');$('#guide-modal').hidden=true;}
$('#open-guide').addEventListener('click',openGuide);$('#mobile-guide').addEventListener('click',openGuide);$('#close-guide').addEventListener('click',closeGuide);$('#guide-next').addEventListener('click',()=>{if(guidePage===0){guidePage=1;renderGuide();}else closeGuide();});$('#guide-modal').addEventListener('click',event=>{if(event.target===$('#guide-modal'))closeGuide();});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('#guide-modal').hidden)closeGuide();});
render();if(!localStorage.getItem(GUIDE_KEY))openGuide();setInterval(()=>{render();},60000);
